### ISSUE TITLE
seek doesn't work on Windows

### ISSUE THREAD

**Issue by mscdex** [baudehlo/node-fs-ext#34]
lseek() triggers a VC++ library assertion with the message `Expression: (_osfile(fh) & FOPEN)` when `fs-ext` is compiled in debug mode. In release mode it just silently crashes.

The same thing happens when you try to call `_get_osfhandle(fd)`, which is strange since libuv opens files on Windows with `_open_osfhandle()` on the handle returned by CreateFileW. The return value is the fd which is used by node, so you would think that `_get_osfhandle()` should work but it doesn't for some reason. I've tried asking in #libuv about it but I guess there aren't many Windows dev gurus in there.

Anyway FWIW I used VC2010 Express with Win7 SDK to compile `fs-ext`.

**Comment by houd1ni** [comment]
Hi all! Today I've built the module on my windows 10, and prove that seek() works just fine.

**Comment by baudehlo** [comment]
OK, closing.
