### ISSUE TITLE
compilation failed against new nan-1.6.1

### ISSUE THREAD

**Issue by pnemade** [baudehlo/node-fs-ext#42]
In Fedora I am maintaining nodej-fs-ext package. I received notification about new tarball release. So, I created new package nodejs-fs-ext-0.4.3 and tried building it. But build failed against nan-1.6.1 module. See the failed https://kojipkgs.fedoraproject.org//work/tasks/1250/8881250/build.log

Can you fix fs-ext-0.4.3 to work against nan-1.6.1?

Thanks.

**Comment by pnemade** [comment]
looks like something changed from 1.4.1 to 1.5.0 nan module

**Comment by baudehlo** [comment]
The build should be tied to Nan 1.4 according to package.json.

**Comment by ggreer** [comment]
@baudehlo is right that fs-ext 0.4.3 should be using nan 1.4. That said, I updated fs-ext to use nan 1.6 in #43. There just hasn't been a new release yet.

**Comment by baudehlo** [comment]
New release is out now.
