### ISSUE TITLE
error installing fs-ext

### ISSUE THREAD

**Issue by jigargosar** [baudehlo/node-fs-ext#8]
npm install fs-ext -g
npm WARN fs-ext@0.2.3 package.json: bugs['web'] should probably be bugs['url']

> fs-ext@0.2.3 install /home/jigar/local/node/lib/node_modules/fs-ext
> node-waf configure build

Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /home/jigar/local/node/lib/node_modules 
Checking for node prefix                 : ok /home/jigar/local/node 
'configure' finished successfully (0.260s)
Waf: Entering directory `/home/jigar/local/node/lib/node_modules/fs-ext/build'
[1/2] cxx: fs-ext.cc -> build/default/fs-ext_1.o
../fs-ext.cc: In function ‘v8::Handle<v8::Value> Flock(const v8::Arguments&)’:
../fs-ext.cc:259:61: error: invalid conversion from ‘void (*)(eio_req*)’ to ‘int (*)(eio_req*)’
../fs-ext.cc:259:61: error:   initializing argument 1 of ‘eio_req* eio_custom(int (*)(eio_req*), int, int (*)(eio_req*), void*)’
../fs-ext.cc: In function ‘v8::Handle<v8::Value> Seek(const v8::Arguments&)’:
../fs-ext.cc:325:57: error: invalid conversion from ‘void (*)(eio_req*)’ to ‘int (*)(eio_req*)’
../fs-ext.cc:325:57: error:   initializing argument 1 of ‘eio_req* eio_custom(int (*)(eio_req*), int, int (*)(eio_req*), void*)’
../fs-ext.cc: In function ‘v8::Handle<v8::Value> UTime(const v8::Arguments&)’:
../fs-ext.cc:382:59: error: invalid conversion from ‘void (*)(eio_req*)’ to ‘int (*)(eio_req*)’
../fs-ext.cc:382:59: error:   initializing argument 1 of ‘eio_req* eio_custom(int (*)(eio_req*), int, int (*)(eio_req*), void*)’
../fs-ext.cc: In function ‘v8::Handle<v8::Value> StatVFS(const v8::Arguments&)’:
../fs-ext.cc:430:63: error: invalid conversion from ‘void (*)(eio_req*)’ to ‘int (*)(eio_req*)’
../fs-ext.cc:430:63: error:   initializing argument 1 of ‘eio_req* eio_custom(int (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory `/home/jigar/local/node/lib/node_modules/fs-ext/build'
Build failed:  -> task failed (err #1): 
	{task: cxx fs-ext.cc -> fs-ext_1.o}
npm ERR! error installing fs-ext@0.2.3 Error: fs-ext@0.2.3 install: `node-waf configure build`
npm ERR! error installing fs-ext@0.2.3 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing fs-ext@0.2.3     at ChildProcess.<anonymous> (/home/jigar/local/node/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing fs-ext@0.2.3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing fs-ext@0.2.3     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! fs-ext@0.2.3 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the fs-ext@0.2.3 install script.
npm ERR! This is most likely a problem with the fs-ext package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fs-ext
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 2.6.38-11-generic
npm ERR! command "node" "/home/jigar/local/node/bin/npm" "install" "fs-ext" "-g"
npm ERR! cwd /media/sf_talk_to_lookup
npm ERR! node -v v0.4.12
npm ERR! npm -v 1.0.106
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /media/sf_talk_to_lookup/npm-debug.log
npm not ok

**Comment by baudehlo** [comment]
I'm pretty sure this is fixed with the port to using Nan. Please re-open if it's still an issue.
