### ISSUE TITLE
F_WRLCK not added to constants in Node.js 11

### ISSUE THREAD

**Issue by alanshaw** [baudehlo/node-fs-ext#81]
In Node.js 11:

```console
$ node
> const fs = require('fs-ext')
undefined
> require('constants').F_WRLCK
undefined
> process.versions.node
'11.10.0'
```

In Node.js 10:

```console
$ node
> const fs = require('fs-ext')
undefined
> require('constants').F_WRLCK
3
> process.versions.node
'10.15.1'
```

**Comment by alanshaw** [comment]
Also, `require('constants')` has been deprecated since Node.js 6 and it should be added to `require('fs').constants` or `require('fs-ext').constants` instead (I think the latter would make more sense).

**Comment by ikokostya** [comment]
> o `require('fs-ext').constants` instead (I think the latter would make more sense).

I totally agree. Created separate issue for this https://github.com/baudehlo/node-fs-ext/issues/89
