### ISSUE TITLE
flock not working with fs.open ?!

### ISSUE THREAD

**Issue by GeorgeFlorian** [baudehlo/node-fs-ext#97]
Hello !  
I am trying this module in a simple express server, but `flock` doesn't seem to work with `fs.open`.

The following code doesn't work as it returns `TypeError: Bad argument`
```
  // open file
  const networkFile = fs.open(path.join(__dirname + '/test.txt'), "w+", (err, f) => {
    if(err) {
      console.log("Could not open file.");
    }
    console.log(f);
  });
  // lock file
  flock(networkFile, 'ex', (err) => {
    if(err) {
      return console.log("Could not lock file.");
    }
    // file is locked
    console.log("File is locked.");
  });
```

Chaning from `fs.open` to `fs.openSync` made `flock` work, so the following code works:
```
const networkFile = fs.openSync(path.join(__dirname + '/test.txt'), "w+");
```

Is this normal behavior ? Should `fs.open` not work with `flock` ? And if that's the case, can somebody explain as to why ?

Thank you.

**Comment by baudehlo** [comment]
You've misunderstood how callbacks work. Please do a node.js fundamentals
course before continuing.

**Comment by GeorgeFlorian** [comment]
I certainly do need to take that, but unfortunately I don't have the time.

I have found examples of `fs.open` here https://www.geeksforgeeks.org/node-js-fs-open-method/
If I am wrong, that means that whoever wrote that example is also in the wrong.
